conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test, permission_required, login_required
from ikwen_webnode.webnode.views import FlatPageView

from doing.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Doing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^trade/', include('ikwen_kakocase.trade.urls', namespace='trade')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^marketing/', include('ikwen_kakocase.commarketing.urls', namespace='marketing')),
    url(r'^sales/', include('ikwen_kakocase.sales.urls', namespace='sales')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^daraja/', include('daraja.urls', namespace='daraja')),

    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^home/$', login_required(Home.as_view()), name='home'),
    url(r'^', include('doing.urls', namespace='doing')),

)

doing/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from doing.views import Welcome, DownloadGuide, VoteList, ChangeProject, SubmitProject, \
    ProjectList, SubmitVote, ChangeCompetitor, CompetitorList, ChangeCategory, CategoryList, Partnership,\
    ChangeReaction, ReactionList, ChangeNews, NewsList, Thanks

urlpatterns = patterns(
    '',
    url(r'^$', Welcome.as_view(), name='welcome'),
    url(r'^downloadGuide/$', login_required(DownloadGuide.as_view()), name='download_guide'),

    url(r'^changeCompetitor/$', permission_required('doing.ik_manage_competitor')(ChangeCompetitor.as_view()), name='change_competitor'),
    url(r'^changeCompetitor/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_competitor')(ChangeCompetitor.as_view()), name='change_competitor'),
    url(r'^CompetitorList/$', permission_required('doing.ik_manage_competitor')(CompetitorList.as_view()), name='competitor_list'),

    url(r'^changeReaction/$', permission_required('doing.ik_manage_reaction')(ChangeReaction.as_view()), name='change_reaction'),
    url(r'^changeReaction/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_reaction')(ChangeReaction.as_view()), name='change_reaction'),
    url(r'^ReactionList/$', permission_required('doing.ik_manage_reaction')(ReactionList.as_view()), name='reaction_list'),

    url(r'^changeCategory/$', permission_required('doing.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^changeCategory/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^CategoryList/$', permission_required('doing.ik_manage_category')(CategoryList.as_view()), name='category_list'),

    url(r'^changeNews/$', permission_required('doing.ik_manage_news')(ChangeNews.as_view()), name='change_news'),
    url(r'^changeNews/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_news')(ChangeNews.as_view()), name='change_news'),
    url(r'^NewsList/$', permission_required('doing.ik_manage_news')(NewsList.as_view()), name='news_list'),

    url(r'^changeProject/$', permission_required('doing.ik_manage_project')(login_required(ChangeProject.as_view())), name='change_project'),
    url(r'^submitProject/$', login_required(SubmitProject.as_view()), name='submit_project'),
    url(r'^changeProject/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_project')(login_required(ChangeProject.as_view())), name='change_project'),
    url(r'^projectList/$', permission_required('doing.ik_manage_project')(login_required(ProjectList.as_view())), name='project_list'),

    url(r'^voteList/$', permission_required('doing.ik_manage_vote')(VoteList.as_view()), name='vote_list'),
    url(r'^submitVote/$', SubmitVote.as_view(), name='submit_vote'),

    url(r'^partnership/$', Partnership.as_view(), name='partnership'),
    url(r'^thanks/$', Thanks.as_view(), name='thanks'),
)

doing/models.py
from django.db import models
from django.utils.translation import gettext as _
from djangotoolbox.fields import EmbeddedModelField, ListField

from ikwen.accesscontrol.models import Member
from ikwen.core.constants import GENDER_CHOICES
from ikwen.core.utils import get_service_instance, add_database
from ikwen.core.models import Model, AbstractConfig, Service
from ikwen.core.fields import MultiImageField, FileField


class Category(Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
       return self.name


class Competitor(Model):
    member = models.ForeignKey(Member)
    birth_town = models.CharField(_('Town of birth'), max_length=100)
    residence = models.CharField(_('Residence'), max_length=100)
    occupation = models.CharField(_('Occupation'), null=True, blank=True, max_length=100)
    school = models.CharField(_('School'), null=True, blank=True, max_length=100)
    study_field = models.CharField(_('Field of study'), null=True, blank=True, max_length=100)

    def __unicode__(self):
        return self.member.first_name


class Project(Model):
    name = models.CharField(max_length=150)
    promoter = models.ForeignKey(Competitor, null=True, blank=True)
    category = models.ForeignKey(Category, null=True)
    team_mate_list = ListField(EmbeddedModelField('accesscontrol.Member'), null=True, blank=True)
    description = models.TextField(_('Describe your project'), max_length=100)
    attachment = FileField(_('Attachment'), allowed_extensions=['doc', 'docx', 'pdf', 'ppt', 'odt'], upload_to='Projects')

    def __unicode__(self):
        return "%s - %s" % (self.name, self.promoter.member.full_name)

    # def get_obj_details(self):
    #     if self.team_mate_list:
    #         team_mates = ",".join([mate for mate in self.team_mate_list])
    #         return "Team-mates: " + team_mates

    def get_obj_details(self):
        vote_count = self.vote_set.count()
        if vote_count > 0:
            return "%d people reacted" % vote_count
        else:
            return "No reaction"


class Vote(Model):
    voter = models.ForeignKey(Member)
    project = models.ForeignKey(Project)

    def __unicode__(self):
        return "%s voted for %s" % (self.voter.full_name, self.project.name)


class Reaction(Model):
    member = models.ForeignKey(Member)
    project = models.ForeignKey(Project)
    comment = models.CharField(max_length=400, blank=True, null=True)
    liked = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s reacted on %s" % (self.member.full_name, self.project.name)


class Partnership(Model):
    UPLOAD_TO = 'Partnerships'
    partner = models.ForeignKey(Member)
    contract = FileField(_('Contract'), allowed_extensions=['doc', 'pdf', 'docx', 'odt'], upload_to=UPLOAD_TO)

    def __unicode__(self):
        return self.partner


class TrainingModule(Model):
    UPLOAD_TO = 'Training_docs'
    name = models.CharField(_("Training module's name"), max_length=250)
    document = FileField(_('Training document'), allowed_extensions=['doc', 'pdf', 'docx', 'odt'],
                         upload_to=UPLOAD_TO + '/Images')
    duration = models.PositiveIntegerField(_('Training module'), help_text=_('Rated in hours'), default=0)


class News(Model):
    UPLOAD_TO = 'ChallengeSteps'
    name = models.CharField(_("Name"), max_length=250)
    resume = models.TextField(_('Resume'))
    image = FileField(blank=True, null=True, allowed_extensions=['jpg', 'jpeg', 'png', 'heic'],
                      upload_to=UPLOAD_TO + '/Images', help_text=_("Upload a single image file here"))
    video = FileField(blank=True, null=True, allowed_extensions=['mp4', 'avi', 'webm', 'mov', 'ogg', 'wmv'],
                      upload_to=UPLOAD_TO + '/Videos', help_text=_("Upload a single video file here"))

doing/views.py
import json
import logging
from threading import Thread


from django.utils.translation import activate, ugettext as _
from django.shortcuts import render, get_object_or_404


from django.core.mail.message import EmailMessage
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.views.generic import TemplateView

from ikwen.accesscontrol.backends import UMBRELLA
from ikwen.accesscontrol.models import Member

from ikwen.core.views import HybridListView, ChangeObjectBase, logger
from ikwen.core.utils import get_model_admin_instance, get_preview_from_extension, get_service_instance, add_database, \
    get_mail_content, send_push

from conf import settings
from doing.models import Project, Vote, TrainingModule, News, Competitor, Category, Reaction
from doing.admin import ProjectAdmin, VoteAdmin, TrainingModuleAdmin, \
    NewsAdmin, CompetitorAdmin, CategoryAdmin, ReactionAdmin

logger = logging.getLogger('ikwen')


class Welcome(TemplateView):
    template_name = 'doing/welcome.html'


class Home(TemplateView):
    template_name = 'doing/home.html'


class DownloadGuide(TemplateView):
    template_name = 'doing/download_guide.html'


class VoteList(HybridListView):
    model = Vote
    model_admin = VoteAdmin


class SubmitVote(ChangeObjectBase):
    model = Vote
    model_admin = VoteAdmin
    template_name = 'doing/submit_vote.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        comment = request.GET.get('comment')
        project_id = request.GET.get('project_id')
        is_vote = request.GET.get('is_vote')
        if project_id:
            project = Project.objects.get(pk=project_id)
            if comment:
                try:
                    Reaction.objects.get(member=user, project=project)
                    return HttpResponse(json.dumps({'error': True}), content_type='application/json')
                except:
                    Reaction.objects.create(member=user, project=project, comment=comment)
                    return HttpResponse(json.dumps({'success': True}), content_type='application/json')
            if is_vote:
                try:
                    Vote.objects.get(voter=user, project=project)
                    return HttpResponse(json.dumps({'error': True}), content_type='application/json')
                except:
                    Vote.objects.create(voter=user, project=project)
                    return HttpResponse(json.dumps({'success': True}), content_type='application/json')
        return super(SubmitVote, self).get(request, *args, **kwargs)


class ProjectList(HybridListView):
    model = Project
    model_admin = ProjectAdmin
    list_filter = ('category',)
    html_results_template_name = "doing/snippets/project_list_results.html"


class ChangeProject(ChangeObjectBase):
    model = Project
    model_admin = ProjectAdmin


class SubmitProject(ChangeObjectBase):
    model = Project
    model_admin = ProjectAdmin
    template_name = 'doing/submit_project.html'

    def after_save(self, request, obj, *args, **kwargs):
        member = request.user
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        gender = request.POST.get('gender')
        birthday = request.POST.get('birthday')

        if first_name:
            member.first_name = first_name
        if last_name:
            member.last_name = last_name
        if birthday:
            birthday = birthday.split('-')
            member.birthday = birthday[0] + birthday[1]
        if gender:
            member.gender = gender
        member.save()

        birth_town = request.POST.get('birth_town')
        residence = request.POST.get('residence')
        occupation = request.POST.get('occupation')
        school = request.POST.get('school')
        study_field = request.POST.get('study_field')

        try:
            competitor = Competitor.objects.get(member=member)
        except:
            competitor = Competitor.objects.create(member=member)
        if birth_town:
            competitor.birth_town = birth_town
        if residence:
            competitor.residence = residence
        if occupation:
            competitor.occupation = occupation
        if school:
            competitor.school = school
        if study_field:
            competitor.study_field = study_field

        competitor.save()
        obj.promoter = competitor
        category_id = request.POST.get('category')
        if category_id:
            category = Category.objects.get(pk=category_id)
            obj.category = category
        team_mates = request.POST.get('team_mates_ids')
        if team_mates:
            obj.team_mate_list = [Member.objects.get(pk=mate) for mate in team_mates.split(',')]
        weblet = get_service_instance()
        obj.save()
        staff_emails = [member.email for member in Member.objects.using(UMBRELLA).filter(is_staff=True)]

        subject = _("Thank you for your application")
        cta_url = "https://tchopetyamo.com"
        leader = obj.promoter.member
        try:
            html_content = get_mail_content(subject, template_name='doing/mails/thanks.html',
                                            extra_context={'applicant_name': leader.full_name,
                                                           'category': obj.category,
                                                           'cta_url': cta_url})
            sender = 'Doing @ %s <no-reply@%s>' % ("tchopetyamo", "tchopetyamo.com")
            msg = EmailMessage(subject, html_content, sender, [leader.email])
            msg.bcc = staff_emails
            msg.content_subtype = "html"
            if getattr(settings, 'UNIT_TESTING', False):
                msg.send()
            else:
                Thread(target=lambda m: m.send(), args=(msg,)).start()
        except:
            logger.error("%s - Failed to send notice mails to %s." % (weblet, leader.first_name), exc_info=True)
        body = _('Congratulation!!! We received your application')
        if obj.category:
            body = _('Congratulation!!! We received your application in %(name)s' % {
                'name': obj.category.name})
        send_push(weblet, leader, subject, body, cta_url)
        return HttpResponseRedirect(reverse('doing:thanks'))


class Partnership(TemplateView):
    template_name = 'doing/partnership.html'


class TrainingModuleList(HybridListView):
    model = TrainingModule
    model_admin = TrainingModuleAdmin


class ChangeCompetitor(ChangeObjectBase):
    model = Competitor
    model_admin = CompetitorAdmin


class CompetitorList(HybridListView):
    model = Competitor
    model_admin = CompetitorAdmin


class ChangeCategory(ChangeObjectBase):
    model = Category
    model_admin = CategoryAdmin


class CategoryList(HybridListView):
    model = Category
    model_admin = CategoryAdmin


class ChangeReaction(ChangeObjectBase):
    model = Reaction
    model_admin = ReactionAdmin


class ReactionList(HybridListView):
    model = Reaction
    model_admin = ReactionAdmin


class NewsList(HybridListView):
    model = News


class ChangeNews(ChangeObjectBase):
    model = News
    model_admin = NewsAdmin


class Thanks(TemplateView):
    template_name = 'doing/thanks.html'

doing/templates/doing/snippets/colors_and_icons.html
{% load i18n static cache %}

<meta name="theme-color" content="#233682">

<meta name="msapplication-TileColor" content="#233682">
<meta name="msapplication-navbutton-color" content="#233682">
<meta name="msapplication-TileImage" content="{% static 'doing/img/logo.png' %}">
{#<meta name="msapplication-TileImage" content="{% static 'doing/img/job_config-144x144.png' %}">#}

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#233682">

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'doing/img/logo.png' %}">
{#<link rel="apple-touch-icon" sizes="180x180" href="{% static 'doing/img/job_config-180x180.png' %}">#}
{#<link rel="shortcut icon" type="image/png" href="{% static 'foulassi/icons/icon-192x192.png' %}">#}
<link rel="shortcut icon" type="image/png" sizes="144x144" href="{% static 'doing/img/logo.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'doing/img/logo.png' %}">
{#<link rel="icon" type="image/png" sizes="96x96" href="{% static 'doing/img/doing-logo.png-96x96.png' %}">#}
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'doing/img/logo.png' %}">
{#<link rel="icon" type="image/png" sizes="32x32" href="{% static 'doing/img/doing-logo.png-32x32.png' %}">#}

doing/templates/doing/snippets/model_admin_form.html
{% load static i18n humanize %}
{% with member=request.user %}
<section>
    <h3>{% trans 'Identification' %}</h3>
    <div class="form-group">
        <label for="id_first-name">{% trans "First name :" %}</label>
        <input id="id_first-name" type="text" class="form-control" name="first_name" {% if user.first_name %}disabled="true" value="{{ user.first_name }}"{% endif %}>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_last-name">{% trans "Last name :" %}</label>
        <input id="id_last-name" type="text" class="form-control" name="last_name" {% if user.last_name %}disabled="true" value="{{ user.last_name }}"{% endif %}>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_gender">{% trans "Gender :" %}</label>
        <input id="id_gender" type="text" class="form-control" name="gender" {% if user.gender %}disabled="true" value="{{ user.gender }}"{% endif %}>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_gender">{% trans "Date of birth :" %}</label>
        <input id="id_gender" type="date" class="form-control" name="birthday" {% if user.birthday %}disabled="true" value="{{ user.birthday }}"{% endif %}>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_birth-town">{% trans "Town of birth :" %}</label>
        <input id="id_birth-town" type="text" class="form-control" name="birth_town">
        <div class="clearfix"></div>
    </div>
</section>

<section>
    <h3>{% trans 'Contact' %}</h3>
    <div class="form-group">
        <label for="id_phone">{% trans "Phone :" %}</label>
        <input id="id_phone" type="text" class="form-control" name="phone" {% if user.phone %}disabled="true" value="{{ request.user.phone }}"{% endif %}>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_email">{% trans "Email :" %}</label>
        <input id="id_last-name" type="email" class="form-control" name="email" {% if user.email %} disabled="true" value="{{ request.user.email }}"{% endif %}>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_residence">{% trans "Residence:" %}</label>
        <input id="id_residence" type="text" class="form-control" name="residence">
        <div class="clearfix"></div>
    </div>
</section>


<section>
    <h3>{% trans 'Education' %}</h3>
    <div class="form-group">
        <label for="id_school">{% trans "School :" %}</label>
        <input id="id_school" type="text" class="form-control" name="school">
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_study-field">{% trans "Field of study :" %}</label>
        <input id="id_study-field" type="text" class="form-control" name="study_field">
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_occupation">{% trans "Occupation :" %}</label>
        <input id="id_occupation" type="text" class="form-control" name="occupation">
        <div class="clearfix"></div>
    </div>
</section>


<section id="project-description" style="padding-bottom: 5vh">
    <h3>{% trans 'Describe your project' %}</h3>
    <div class="form-group">
        <label for="id_category">{% trans 'Category :' %}</label>
        <select id="id_category" class="form-control" name="category">
            {% for category in category_list %}
                <option value="{{ category.id }}">{{ category }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_name">{% trans "Name :" %}</label>
        <input id="id_name" type="text" class="form-control" name="name">
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="id_description">{% trans "Description :" %}</label>
        <textarea id="id_description" class="form-control" name="description" style="height: 200px" placeholder="{% trans 'Describe your project in 100 words' %}"></textarea>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
        <label for="team-mates">{% trans "Add team-mates :" %}</label>
        <input id="mate" type="text" class="form-control">
        <input id="team-mates" type="hidden" name="team_mates_ids" class="form-control">
        <div class="results team-mates has-shade" style="display: none" data-min-search-chars="2">
            {% include 'core/snippets/spinner.html' %}
            <ul style="padding-left: 0">
                <li class="member tpl" style="display: none">
                    <div style="display: block">
                        <span class="photo logo bg-img" style="background-image: url({% static 'ikwen/img/no_photo.png' %})"></span>
                        <div style="float: left; margin-left: 30px">
                            <span class="full_name"></span>
                            <p class="about short_description"></p>
                        </div>
                        <a class="trash tpl" style="float: right;">
                            <i class="glyphicon glyphicon-trash" title="{% trans "Delete item" %}" style="margin-right: 10px;"></i>
                        </a>
                    </div>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <ul id="team" style="list-style: none; padding: 20px 0">
        <div class="clearfix"></div>
    </ul>
    <div class="clearfix"></div>
</section><div class="clearfix"></div>
{% endwith %}


{% block js %}
    <script src="{% static 'ikwen/js/ikwen-util.js' %}?v=20.10.30"></script>
    <script>
        $('#project-description').on('click', '.continue', function() {
            $(this).hide();
            $('.subscription-details').show();
        });
        $('#mate').keyup(function() {
            var val = $(this).val();
            if (val.isValidEmail()) {
                let $teamMates = $('#team-mates');
                $teamMates.val($teamMates.val() + ',' + val);
                $('#project-description .continue').prop('disabled', false);
            } else {
                $('#project-description .continue').prop('disabled', true);
            }
        });
        {% url 'ikwen:member_list' as list_members_url %}
        var searchDescriptor = [{
            endpoint: '{{ list_members_url }}',
            resultTplSelector: '.results.team-mates li.member',
            maxChars: function() {
                // The max number of characters that will be taken into consideration
                // in the string typed by user to do the search. Characters above that
                // limit will be ignored.
                return Math.max($('#mate').val().length, 4);
            }
        }];
        $('#mate').focusout(function() {$('.results.team-mates').fadeOut()});

        ikwen.setupSearch('#mate', '.results.team-mates', searchDescriptor);

        $('.results.team-mates *').on('click', () => {
            let $teamMates = $('#team-mates'), teamMates = $teamMates.val().split(','),
                $mate = $('.results.team-mates .member:not(.tpl)'),
                mateId = $mate.data('id'), i=0;
            while (i < teamMates.length){
                if (mateId === teamMates[i]) break;
                i++;
            }
            if (i === teamMates.length){
                if ($teamMates.val() === '')
                    $teamMates.val(mateId);
                else
                    $teamMates.val($teamMates.val() + ',' + mateId);
                $mate.clone().show().appendTo('#team').find('.trash').show().removeClass('tpl');
            }
        });
        $('#team').on('click', '.trash', (e) => {
           let $teamMates = $('#team-mates'), teamMates = $teamMates.val().split(','),
               i = 0, $mate = $(e.target).parents('.member:not(.tpl)'), mateId = $mate.prop('id');
           while (i < teamMates.length){
               if (mateId === teamMates[i]){
                   $teamMates.val($teamMates.val().replace(',' + mateId , ''));
                   break;
               }
               i++;
           }
           $mate.remove();
        });
    </script>
{% endblock %}

doing/templates/doing/snippets/project_list_results.html
{% load i18n static humanize %}
{% include 'core/snippets/spinner.html' %}
<link rel="stylesheet" href="{% static 'doing/css/doing-admin.css' %}">
<ul class="object-list list-group">
    {% for obj in objects_page.object_list %}
    {% url 'doing:change_project' obj.id as obj_url %}
    <li class="ik-li list-group-item {{ obj.status }}" id="{{ obj.id }}" data-id="{{ obj.id }}">
        {% if obj.category %}
            {% with category=obj.category.name %}
                {% if category == 'ICT' %}
                    <a href="{{ obj_url }}" class="profile text-has-shade aspect aspect-ict">{% trans 'ICT' %}</a>
                {% elif category == 'Agro Industry' %}
                    <a href="{{ obj_url }}" class="profile text-has-shade aspect aspect-ai">{% trans 'A.I' %}</a>
                {% elif category == 'Art and Culture' %}
                    <a href="{{ obj_url }}" class="profile text-has-shade aspect aspect-ac">{% trans 'A & C' %}</a>
                {% elif category == 'Machinery' %}
                    <a href="{{ obj_url }}" class="profile text-has-shade aspect aspect-m">{% trans 'M' %}</a>
                {% endif %}
            {% endwith %}
        {% endif %}
        <div class="info">
            <a href="{{ obj_url }}" class="title">{{ obj }}</a>
            {% with obj_details=obj.get_obj_details %}
                {% if obj_details %}
                    <p class="about text-muted">{{ obj_details|safe }}</p>
                {% endif %}
            {% endwith %}
            <p class="text-muted">
                <strong>{% trans 'Team-mates:' %}</strong>
                {% for mate in obj.team_mate_list %}
                    {{ mate.full_name }}
                {% endfor %}
            </p>
        </div>
        <div class="actions">
            {% if has_is_active_field %}
                {% if obj.is_active %}
                    <i class="action glyphicon glyphicon-ok toggle active off" title="{% trans "Deactivate" %}"></i>
                {% else %}
                    <i class="action glyphicon glyphicon-ok toggle active on" title="{% trans "Activate" %}"></i>
                {% endif %}
            {% endif %}
            <i class="glyphicon glyphicon-trash trash" title="{% trans "Delete item" %}"></i>
        </div>
    </li>
    {% endfor %}
</ul>
{% if objects_page.paginator.num_pages > 1 %}
<ul class="pagination">
    {% if objects_page.paginator.num_pages > max_visible_page_count and page_range.0 >= max_visible_page_count  %}
        <li class="page" data-val="first"><a href="javascript:;" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
    {% endif %}
    {% for page in page_range %}
        <li class="page{% if page == objects_page.number %} active{% endif %}" data-val="{{ page }}">
            <a href="javascript:;">
                {{ page }} {% if page == objects_page.number %}<span class="sr-only">(current)</span>{% endif %}
            </a>
        </li>
    {% endfor %}
    {% if objects_page.paginator.num_pages > max_visible_page_count and max_page < objects_page.paginator.num_pages %}
        <li class="page{% if max_page == objects_page.paginator.num_pages %} disabled{% endif %}" data-val="-1"><a href="javascript:;" aria-label="Next"><span aria-hidden="true">»</span></a></li>
    {% endif %}
</ul>
{% endif %}
<div id="page-navigation" class="text-muted">
    {% if objects_page.paginator.num_pages > 1 %}
        <p>{% blocktrans with count=objects_page.paginator.count start=objects_page.start_index end=objects_page.end_index %}
            {{ start }} – {{ end }} of {{ count }} results{% endblocktrans %}</p>
    {% else %}
        <p>{% blocktrans with count=objects_page.paginator.count %}{{ count }} results{% endblocktrans %}</p>
    {% endif %}
</div>