conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test, permission_required, login_required
from ikwen_webnode.webnode.views import FlatPageView

from doing.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Doing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^trade/', include('ikwen_kakocase.trade.urls', namespace='trade')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^marketing/', include('ikwen_kakocase.commarketing.urls', namespace='marketing')),
    url(r'^sales/', include('ikwen_kakocase.sales.urls', namespace='sales')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^daraja/', include('daraja.urls', namespace='daraja')),

    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^home/$', login_required(Home.as_view()), name='home'),
    url(r'^', include('doing.urls', namespace='doing')),

)

doing/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from doing.views import Welcome, DownloadGuide, VoteList, ChangeProject, SubmitProject, \
    ProjectList, SubmitVote, ChangeCompetitor, CompetitorList, ChangeCategory, CategoryList, Partnership,\
    ChangeReaction, ReactionList, ChangeNews, NewsList, Thanks

urlpatterns = patterns(
    '',
    url(r'^$', Welcome.as_view(), name='welcome'),
    url(r'^downloadGuide/$', login_required(DownloadGuide.as_view()), name='download_guide'),

    url(r'^changeCompetitor/$', permission_required('doing.ik_manage_competitor')(ChangeCompetitor.as_view()), name='change_competitor'),
    url(r'^changeCompetitor/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_competitor')(ChangeCompetitor.as_view()), name='change_competitor'),
    url(r'^CompetitorList/$', permission_required('doing.ik_manage_competitor')(CompetitorList.as_view()), name='competitor_list'),

    url(r'^changeReaction/$', permission_required('doing.ik_manage_reaction')(ChangeReaction.as_view()), name='change_reaction'),
    url(r'^changeReaction/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_reaction')(ChangeReaction.as_view()), name='change_reaction'),
    url(r'^ReactionList/$', permission_required('doing.ik_manage_reaction')(ReactionList.as_view()), name='reaction_list'),

    url(r'^changeCategory/$', permission_required('doing.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^changeCategory/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^CategoryList/$', permission_required('doing.ik_manage_category')(CategoryList.as_view()), name='category_list'),

    url(r'^changeNews/$', permission_required('doing.ik_manage_news')(ChangeNews.as_view()), name='change_news'),
    url(r'^changeNews/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_news')(ChangeNews.as_view()), name='change_news'),
    url(r'^NewsList/$', permission_required('doing.ik_manage_news')(NewsList.as_view()), name='news_list'),

    url(r'^changeProject/$', permission_required('doing.ik_manage_project')(login_required(ChangeProject.as_view())), name='change_project'),
    url(r'^submitProject/$', login_required(SubmitProject.as_view()), name='submit_project'),
    url(r'^changeProject/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_project')(login_required(ChangeProject.as_view())), name='change_project'),
    url(r'^projectList/$', permission_required('doing.ik_manage_project')(login_required(ProjectList.as_view())), name='project_list'),

    url(r'^voteList/$', permission_required('doing.ik_manage_vote')(VoteList.as_view()), name='vote_list'),
    url(r'^submitVote/$', SubmitVote.as_view(), name='submit_vote'),

    url(r'^partnership/$', Partnership.as_view(), name='partnership'),
    url(r'^thanks/$', Thanks.as_view(), name='thanks'),
)

doing/models.py
from django.db import models
from django.utils.translation import gettext as _
from djangotoolbox.fields import EmbeddedModelField, ListField

from ikwen.accesscontrol.models import Member
from ikwen.core.constants import GENDER_CHOICES
from ikwen.core.utils import get_service_instance, add_database
from ikwen.core.models import Model, AbstractConfig, Service
from ikwen.core.fields import MultiImageField, FileField


class Category(Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
       return self.name


class Competitor(Model):
    member = models.ForeignKey(Member)
    birth_town = models.CharField(_('Town of birth'), max_length=100)
    residence = models.CharField(_('Residence'), max_length=100)
    occupation = models.CharField(_('Occupation'), null=True, blank=True, max_length=100)
    school = models.CharField(_('School'), null=True, blank=True, max_length=100)
    study_field = models.CharField(_('Field of study'), null=True, blank=True, max_length=100)

    def __unicode__(self):
        return self.member.first_name


class Project(Model):
    name = models.CharField(max_length=150)
    promoter = models.ForeignKey(Competitor, null=True, blank=True)
    category = models.ForeignKey(Category, null=True)
    team_mate_list = ListField(EmbeddedModelField('accesscontrol.Member'), null=True, blank=True)
    description = models.TextField(_('Describe your project'), max_length=100)
    attachment = FileField(_('Attachment'), allowed_extensions=['doc', 'docx', 'pdf', 'ppt', 'odt'], upload_to='Projects')

    def __unicode__(self):
        return "%s - %s" % (self.name, self.promoter.member.full_name)

    # def get_obj_details(self):
    #     if self.team_mate_list:
    #         team_mates = ",".join([mate for mate in self.team_mate_list])
    #         return "Team-mates: " + team_mates

    def get_obj_details(self):
        vote_count = self.vote_set.count()
        if vote_count > 0:
            return "%d people reacted" % vote_count
        else:
            return "No reaction"


class Vote(Model):
    voter = models.ForeignKey(Member)
    project = models.ForeignKey(Project)

    def __unicode__(self):
        return "%s voted for %s" % (self.voter.full_name, self.project.name)


class Reaction(Model):
    member = models.ForeignKey(Member)
    project = models.ForeignKey(Project)
    comment = models.CharField(max_length=400, blank=True, null=True)
    liked = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s reacted on %s" % (self.member.full_name, self.project.name)


class Partnership(Model):
    UPLOAD_TO = 'Partnerships'
    partner = models.ForeignKey(Member)
    contract = FileField(_('Contract'), allowed_extensions=['doc', 'pdf', 'docx', 'odt'], upload_to=UPLOAD_TO)

    def __unicode__(self):
        return self.partner


class TrainingModule(Model):
    UPLOAD_TO = 'Training_docs'
    name = models.CharField(_("Training module's name"), max_length=250)
    document = FileField(_('Training document'), allowed_extensions=['doc', 'pdf', 'docx', 'odt'],
                         upload_to=UPLOAD_TO + '/Images')
    duration = models.PositiveIntegerField(_('Training module'), help_text=_('Rated in hours'), default=0)


class News(Model):
    UPLOAD_TO = 'ChallengeSteps'
    name = models.CharField(_("Name"), max_length=250)
    resume = models.TextField(_('Resume'))
    image = FileField(blank=True, null=True, allowed_extensions=['jpg', 'jpeg', 'png', 'heic'],
                      upload_to=UPLOAD_TO + '/Images', help_text=_("Upload a single image file here"))
    video = FileField(blank=True, null=True, allowed_extensions=['mp4', 'avi', 'webm', 'mov', 'ogg', 'wmv'],
                      upload_to=UPLOAD_TO + '/Videos', help_text=_("Upload a single video file here"))

doing/views.py
import json
import logging
from threading import Thread


from django.utils.translation import activate, ugettext as _
from django.shortcuts import render, get_object_or_404


from django.core.mail.message import EmailMessage
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.views.generic import TemplateView

from ikwen.accesscontrol.backends import UMBRELLA
from ikwen.accesscontrol.models import Member

from ikwen.core.views import HybridListView, ChangeObjectBase, logger
from ikwen.core.utils import get_model_admin_instance, get_preview_from_extension, get_service_instance, add_database, \
    get_mail_content, send_push

from conf import settings
from doing.models import Project, Vote, TrainingModule, News, Competitor, Category, Reaction
from doing.admin import ProjectAdmin, VoteAdmin, TrainingModuleAdmin, \
    NewsAdmin, CompetitorAdmin, CategoryAdmin, ReactionAdmin

logger = logging.getLogger('ikwen')


class Welcome(TemplateView):
    template_name = 'doing/welcome.html'


class Home(TemplateView):
    template_name = 'doing/home.html'


class DownloadGuide(TemplateView):
    template_name = 'doing/download_guide.html'


class VoteList(HybridListView):
    model = Vote
    model_admin = VoteAdmin


class SubmitVote(ChangeObjectBase):
    model = Vote
    model_admin = VoteAdmin
    template_name = 'doing/submit_vote.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        comment = request.GET.get('comment')
        project_id = request.GET.get('project_id')
        is_vote = request.GET.get('is_vote')
        if project_id:
            project = Project.objects.get(pk=project_id)
            if comment:
                try:
                    Reaction.objects.get(member=user, project=project)
                    return HttpResponse(json.dumps({'error': True}), content_type='application/json')
                except:
                    Reaction.objects.create(member=user, project=project, comment=comment)
                    return HttpResponse(json.dumps({'success': True}), content_type='application/json')
            if is_vote:
                try:
                    Vote.objects.get(voter=user, project=project)
                    return HttpResponse(json.dumps({'error': True}), content_type='application/json')
                except:
                    Vote.objects.create(voter=user, project=project)
                    return HttpResponse(json.dumps({'success': True}), content_type='application/json')
        return super(SubmitVote, self).get(request, *args, **kwargs)


class ProjectList(HybridListView):
    model = Project
    model_admin = ProjectAdmin
    list_filter = ('category',)
    html_results_template_name = "doing/snippets/project_list_results.html"


class ChangeProject(ChangeObjectBase):
    model = Project
    model_admin = ProjectAdmin


class SubmitProject(ChangeObjectBase):
    model = Project
    model_admin = ProjectAdmin
    template_name = 'doing/submit_project.html'

    def after_save(self, request, obj, *args, **kwargs):
        member = request.user
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        gender = request.POST.get('gender')
        birthday = request.POST.get('birthday')

        if first_name:
            member.first_name = first_name
        if last_name:
            member.last_name = last_name
        if birthday:
            birthday = birthday.split('-')
            member.birthday = birthday[0] + birthday[1]
        if gender:
            member.gender = gender
        member.save()

        birth_town = request.POST.get('birth_town')
        residence = request.POST.get('residence')
        occupation = request.POST.get('occupation')
        school = request.POST.get('school')
        study_field = request.POST.get('study_field')

        try:
            competitor = Competitor.objects.get(member=member)
        except:
            competitor = Competitor.objects.create(member=member)
        if birth_town:
            competitor.birth_town = birth_town
        if residence:
            competitor.residence = residence
        if occupation:
            competitor.occupation = occupation
        if school:
            competitor.school = school
        if study_field:
            competitor.study_field = study_field

        competitor.save()
        obj.promoter = competitor
        category_id = request.POST.get('category')
        if category_id:
            category = Category.objects.get(pk=category_id)
            obj.category = category
        team_mates = request.POST.get('team_mates_ids')
        if team_mates:
            obj.team_mate_list = [Member.objects.get(pk=mate) for mate in team_mates.split(',')]
        weblet = get_service_instance()
        obj.save()
        staff_emails = [member.email for member in Member.objects.using(UMBRELLA).filter(is_staff=True)]

        subject = _("Thank you for your application")
        cta_url = "https://tchopetyamo.com"
        leader = obj.promoter.member
        try:
            html_content = get_mail_content(subject, template_name='doing/mails/thanks.html',
                                            extra_context={'applicant_name': leader.full_name,
                                                           'category': obj.category,
                                                           'cta_url': cta_url})
            sender = 'Doing @ %s <no-reply@%s>' % ("tchopetyamo", "tchopetyamo.com")
            msg = EmailMessage(subject, html_content, sender, [leader.email])
            msg.bcc = staff_emails
            msg.content_subtype = "html"
            if getattr(settings, 'UNIT_TESTING', False):
                msg.send()
            else:
                Thread(target=lambda m: m.send(), args=(msg,)).start()
        except:
            logger.error("%s - Failed to send notice mails to %s." % (weblet, leader.first_name), exc_info=True)
        body = _('Congratulation!!! We received your application')
        if obj.category:
            body = _('Congratulation!!! We received your application in %(name)s' % {
                'name': obj.category.name})
        send_push(weblet, leader, subject, body, cta_url)
        return HttpResponseRedirect(reverse('doing:thanks'))


class Partnership(TemplateView):
    template_name = 'doing/partnership.html'


class TrainingModuleList(HybridListView):
    model = TrainingModule
    model_admin = TrainingModuleAdmin


class ChangeCompetitor(ChangeObjectBase):
    model = Competitor
    model_admin = CompetitorAdmin


class CompetitorList(HybridListView):
    model = Competitor
    model_admin = CompetitorAdmin


class ChangeCategory(ChangeObjectBase):
    model = Category
    model_admin = CategoryAdmin


class CategoryList(HybridListView):
    model = Category
    model_admin = CategoryAdmin


class ChangeReaction(ChangeObjectBase):
    model = Reaction
    model_admin = ReactionAdmin


class ReactionList(HybridListView):
    model = Reaction
    model_admin = ReactionAdmin


class NewsList(HybridListView):
    model = News


class ChangeNews(ChangeObjectBase):
    model = News
    model_admin = NewsAdmin


class Thanks(TemplateView):
    template_name = 'doing/thanks.html'

doing/templates/doing/download_guide.html
{% extends 'doing/home.html' %}
{% load static humanize auth_tokens webdesign i18n user_agents staticfiles %}

{% block page_title %}<title>{% trans "Business Challenge - TCHOPETYAMO" %}</title>{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'doing/css/doing.css' %}?v=20.11.11">
    <style>
        #navbar .menu-button * {background-color: #312782!important;}
    </style>
{% endblock %}

{% block page_content %}
    <div class="text-center download-guide">
        <img class="img-responsive " src="{% static 'doing/img/logo.png' %}" height="300" width="300">
        <h4>
            {% blocktrans %}
                Download, then read attentively the guide before subscribe to the challenge.
            {% endblocktrans %}
        </h4>
        <div>
            <a class="btn btn-sm col-sm-6 has-shade btn-download" href="{% get_static_prefix %}doing/document/GUIDE DE CELUI QUI OSE.doc">
                {% trans 'Download' %}
            </a>
        </div>
    </div>
    <div class="clearfix"></div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
            (() => {
               $('.download a').on('click', () => {
                   setTimeout(() => {
                       {% url 'doing:submit_project' as next_url %}
                       window.location.href = {{ next_url }};
                   }, 2000);

               });
            })()
    </script>
{% endblock %}

doing/templates/doing/submit_vote.html
{% extends 'doing/submit_project.html' %}
{% load static humanize i18n webdesign %}

{% block page_title %}<title>{% trans "Vote - Business Challenge - TCHOPETYAMO" %}</title>{% endblock %}

{% block head_style %}
    {{ block.super }}
    <style>
        .ok {background-color: #319dd5}
        .cancel {background-color: #95a5a6}
        .ok, .cancel {color: #fff}
    </style>
{% endblock %}
{% block page_content %}
    <div class="vote">
        <div class="banner">
            <div class="banner-inner">
                <h1 class="text-center text-has-shade">{% trans 'Vote' %}</h1>
            </div>
        </div>
        <div id="admin-content" class="change-form container">
            <div>
                {% for category in category_list %}
                    {% if category.project_set.all|length > 0 %}
                        <h1 class="text-center category-title">{{ category }}</h1>
                        <div>
                            {% for project in category.project_set.all %}
                                <div class="col-sm-4 project-details table-bordered" id="{{ project.id }}" data-name="{{ project.name }}">
                                    <h3 class="text-center">{{ project.name }}</h3>
                                    <p class="text-justify" style="height: 100px">
                                        {{ project.description }}
                                    </p>
                                    <div class="team-mates">
                                        <h4>{% trans 'Team-mates' %}</h4>
                                        {% for mate in project.team_mate_list %}
                                            <span>{{ mate.full_name }}</span>
                                        {% endfor %}
                                    </div>
                                    <div class="reactions">
                                        <div>
                                            <span class="col-xs-4"><i class="far fa-thumbs-up {% for vote in project.vote_set.all %}{% if user == vote.voter %}voted{% endif %}{% endfor %}" title="Vote"></i></span>
                                            <span class="col-xs-4"><i class="fa fa-share-alt" title="Share"></i></span>
                                            <span class="col-xs-4"><i class="fa fa-comment {% for reaction in project.reaction_set.all %}{% if user == reaction.member %}commented{% endif %}{% endfor %}" title="Comment"></i></span>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="share-project">
                                            {% url 'doing:submit_vote' as current_url %}
                                            <div class="tpl share-links has-shade">
                                                <div class="social-icon hidden-xs">
                                                    <div class="fb-share-button col-sm-4" data-href="{{ service.url }}{{ current_url }}#{{ project.id }}" data-layout="button" data-mobile-iframe="true">
                                                        <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php"><i class="fab fa-facebook"></i></a>
                                                    </div>
                                                    <a class="twitter-share-button col-sm-4" href="https://twitter.com/intent/tweet?url={{ service.url }}{{ current_url }}#{{ project.id }}" data-size="small"><i class="fab fa-twitter"></i></a>
                                                    <a class="icon-linkedin share-link col-sm-4" href="http://www.linkedin.com/shareArticle?mini=true&amp;url={{ service.url }}{{ current_url }}#{{ project.id }}" title="Share on LinkedIn" target="_blank" rel="noopener noreferrer"><i class="fab fa-linkedin-in"></i></a>
                                                </div>
                                                <div class="row visible-xs">
                                                    <div class="col-sm-offset-2 col-sm-4 col-xs-4" data-href="{{ service.url }}{{ current_url }}#{{ project.id }}" data-layout="button" data-mobile-iframe="true">
                                                        <a class="product-social-share btn btn-block" target="_blank"  href="https://www.facebook.com/sharer/sharer.php?u={{ service.url }}{{ current_url }}#{{ project.id }}"  style="background: #3b5998;">
                                                            <i class="fab fa-facebook-f"></i>
                                                        </a>
                                                    </div>
                                                    <div class="col-sm-4 col-xs-4">
                                                        <a class="product-social-share btn btn-block" data-toggle="modal" data-target="#twitter-share" href="https://twitter.com/intent/tweet?url={{ service.url }}{{ current_url }}#{{ project.id }}" style="background: #1da1f2;">
                                                            <i class="fab fa-twitter"></i>
                                                        </a>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <button class="product-social-share whatsapp-share btn btn-block" data-toggle="modal" data-target="#whatsapp-share" style="background: #25d366;">
                                                            <i class="fab fa-whatsapp"></i>
                                                        </button>
                                                    </div>
                                                    <div class="clearfix"></div>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                        </div>
                                        <div class="comment-project tpl">
                                            <textarea id="comment" class="input-sm form-control has-shade" style="height: 100px" placeholder="{% trans 'Live a comment here' %}"></textarea>
                                            <button class="btn-primary btn-sm col-xs-12">
                                                {% trans 'ok' %}
                                            </button>
                                            {% include 'core/snippets/spinner.html' %}

                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                    <div class="scores text-muted">
                                        {{ project.vote_set.all|length }} <span>{% trans 'votes' %}</span><i class="fa fa-circle"></i>{{ project.reaction_set.all|length }} <span>{% trans 'comments' %}</span></span>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="clearfix"></div>
                        </div>
                    {% endif %}
                {% endfor %}
                {% if category_list|length == 0 %}
                    <div class="text-muted text-center col-sm-12" style="margin: 10px auto; float: none; height: 200px">
                         <h3>{% trans 'No project submit yet...' %}</h3>
                    </div>
                {% endif %}
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    {#    Modal declaration : BEGIN #}
    <div class="modal fade" id="whatsapp-share" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content modal-info">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{% trans "Share on WhatsApp" %}</h4>
                </div>
                <div class="modal-body text-center">
                    <form onclick="return false" class="form-horizontal">
                        <div class="form-group row">
                            <label for="whatsapp-share-msg" class="col-sm-5 col-md-4">{% trans "Message" %}</label>
                            <div class="col-sm-7 col-md-8">
                                <textarea id="whatsapp-share-msg" style="height: 120px"
                                          class="form-control input-sm">{% blocktrans %}Hello, I'm participating to a challenge of young entrepreneurs projects organized by N SARL. Would you like to help me win this challenge by liking and share to your nearest my project.Thanks you in advance{% endblocktrans %}</textarea>
                            </div>
                        </div>
                    </form>
                    <div class="actions">
                        <div class="col-xs-12 col-sm-4 col-md-3 pull-right action">
                            <button class="btn btn-success btn-block btn-sm ok"
                                    data-dismiss="modal" aria-label="OK">OK</button>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-3 pull-right action">
                            <button class="btn btn-default btn-block btn-sm cancel"
                                    data-dismiss="modal" aria-label="Close">{% trans "Cancel" %}</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    {#    Modal declaration : END #}
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (() => {
            $('body').on('click', (e) => {
                if (!$(e.target).hasClass('fa-share-alt') && ! $(e.target).hasClass('fa-comment')
                    && $(e.target).parents('.comment-project').length <= 0
                    && $(e.target).parents('.share-project').length <= 0){
                    $('.share-links').hide();
                    $('.comment-project').hide();
                }
            });
            $('.fa-share-alt').on('click', (e) => {
                let $parent = $(e.target).parents('.project-details');
                $parent.find('.share-links').show();
                $parent.find('.comment-project').hide();
            });
            $('.fa-comment:not(.commented)').on('click', (e) => {
                let $parent = $(e.target).parents('.project-details');
                $parent.find('.comment-project').show();
                $parent.find('.share-links').hide();
            });
            $('.comment-project:not(.commented) button').on('click', (e) => {
                let $project = $(e.target).parents('.project-details'),
                    project_id = $project.attr('id'),
                    project_name = $project.data('name');
                $project.find('.spinner').show();
                $.getJSON('', {'comment': $project.find('#comment').val(), 'project_id': project_id}, (data) => {
                    if (data.success) {
                        $('.fa-comment').addClass('commented');
                        ikwen.showFloatingNotice("{% trans 'You successfully commented project ' %}" + project_name);
                        $('.comment-project').hide();
                    }
                    if (data.error){
                        $(e.target).addClass('commented');
                        ikwen.showFloatingNotice("{% trans 'You have already commented project ' %}" + project_name);
                        $('.comment-project').hide();
                    }
                    $(e.target).find('.spinner').hide();
                });
            });
            $('.fa-thumbs-up:not(.voted)').on('click', (e) => {
                let project_id = $(e.target).parents('.project-details').attr('id'),
                    project_name = $(e.target).parents('.project-details').data('name');
                $.getJSON('', {'project_id': project_id, 'is_vote': true}, (data) => {
                    if (data.success) {
                        $(e.target).addClass('voted');
                        ikwen.showFloatingNotice("{% trans 'You successfully voted for project ' %}" + project_name);
                    }
                    if (data.error){
                        $(e.target).addClass('voted');
                        ikwen.showFloatingNotice("{% trans 'You have already voted for ' %}" + project_name);
                    }
                });
            });
            $('body').on('click', '#whatsapp-share .btn.ok', () => {
                let msg = $('#whatsapp-share-msg').val(),
                    url = '{{ service.url }}{{ current_url }}#{{ project.id }}';
                window.location = 'https://api.whatsapp.com/send?text=' + url + '%0A%0A' + msg;
            });
        })()
    </script>
{% endblock %}