conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test, permission_required, login_required
from ikwen_webnode.webnode.views import FlatPageView

from doing.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Doing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^currencies/', include('currencies.urls')),

    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^trade/', include('ikwen_kakocase.trade.urls', namespace='trade')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^marketing/', include('ikwen_kakocase.commarketing.urls', namespace='marketing')),
    url(r'^sales/', include('ikwen_kakocase.sales.urls', namespace='sales')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^daraja/', include('daraja.urls', namespace='daraja')),

    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^home/$', login_required(Home.as_view()), name='home'),
    url(r'^', include('doing.urls', namespace='doing')),

)

doing/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from doing.views import Welcome, DownloadGuide, VoteList, ChangeProject, SubmitProject, \
    ProjectList, SubmitVote, ChangeCompetitor, CompetitorList, ChangeCategory, CategoryList, Partnership,\
    ChangeReaction, ReactionList, ChangeNews, NewsList, Thanks

urlpatterns = patterns(
    '',
    url(r'^$', Welcome.as_view(), name='welcome'),
    url(r'^downloadGuide/$', login_required(DownloadGuide.as_view()), name='download_guide'),

    url(r'^changeCompetitor/$', permission_required('doing.ik_manage_competitor')(ChangeCompetitor.as_view()), name='change_competitor'),
    url(r'^changeCompetitor/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_competitor')(ChangeCompetitor.as_view()), name='change_competitor'),
    url(r'^CompetitorList/$', permission_required('doing.ik_manage_competitor')(CompetitorList.as_view()), name='competitor_list'),

    url(r'^changeReaction/$', permission_required('doing.ik_manage_reaction')(ChangeReaction.as_view()), name='change_reaction'),
    url(r'^changeReaction/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_reaction')(ChangeReaction.as_view()), name='change_reaction'),
    url(r'^ReactionList/$', permission_required('doing.ik_manage_reaction')(ReactionList.as_view()), name='reaction_list'),

    url(r'^changeCategory/$', permission_required('doing.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^changeCategory/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^CategoryList/$', permission_required('doing.ik_manage_category')(CategoryList.as_view()), name='category_list'),

    url(r'^changeNews/$', permission_required('doing.ik_manage_news')(ChangeNews.as_view()), name='change_news'),
    url(r'^changeNews/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_news')(ChangeNews.as_view()), name='change_news'),
    url(r'^NewsList/$', permission_required('doing.ik_manage_news')(NewsList.as_view()), name='news_list'),

    url(r'^changeProject/$', permission_required('doing.ik_manage_project')(login_required(ChangeProject.as_view())), name='change_project'),
    url(r'^submitProject/$', login_required(SubmitProject.as_view()), name='submit_project'),
    url(r'^changeProject/(?P<object_id>[-\w]+)$', permission_required('doing.ik_manage_project')(login_required(ChangeProject.as_view())), name='change_project'),
    url(r'^projectList/$', permission_required('doing.ik_manage_project')(login_required(ProjectList.as_view())), name='project_list'),

    url(r'^voteList/$', permission_required('doing.ik_manage_vote')(VoteList.as_view()), name='vote_list'),
    url(r'^submitVote/$', SubmitVote.as_view(), name='submit_vote'),

    url(r'^partnership/$', Partnership.as_view(), name='partnership'),
    url(r'^thanks/$', Thanks.as_view(), name='thanks'),
)

templates/website/snippets/edge_panel.html
{% load i18n humanize staticfiles cache auth_tokens %}
<div class="edge-panel-left-container visible-xs">
    <div id="side-nav" class="edge-panel-left subtle-shade" style="margin-left: -300px">
        <div class="wrapper">
            <div class="stage">
                <div class="top-edge-panel" style>
                    <div class="panel-top">
                    <img src="{% static 'doing/img/logo.png' %}" class="img-responsive text-center" style="margin:auto; width: 60%">
                </div>
                <div class="divider"></div>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'doing:download_guide' %}">{% trans "Registration" %}</a></li>
                        <li><a href="{% url 'doing:submit_vote' %}">{% trans "Vote" %}</a></li>
                        <li><a href="{% url 'doing:submit_vote' %}">{% trans "Infos" %}</a></li>
                        <li><a href="{% url 'doing:partnership' %}">{% trans "Partnership" %}</a></li>
                        <div class="divider"></div>
                        <li><a href="http://blog.ikwen.com">{% trans 'Blog' %}</a> </li>
                        <li><a href="http://support.ikwen.com">{% trans 'Support' %}</a> </li>
{#                        <li><a href="{% url 'about' %}">{% trans 'About' %}</a> </li>#}
{#                        <li><a href="{% url 'terms_and_conditions' %}">{% trans 'Terms & conditions' %}</a> </li>#}
                        {% if agreement_page %}
{#                            <li><a href="{% url 'flatpage' agreement_page.url %}">{{ agreement_page.title }}</a></li>#}
                        {% endif %}
                    </ul>
                    <div class="clearfix"></div>

                    <div class="social-icon">
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.linkedin.com/company/18357139/"target="_blank" class="ico ico-linkedin"><i class="fab fa-linkedin-in"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://twitter.com/ikwenSARL"target="_blank" class="ico ico-twitter"><i class="fab fa-twitter"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.facebook.com/Ikwen.SARL" target="_blank" class="ico ico-facebook"><i class="fab fa-facebook"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.youtube.com/channel/UCzhHrosFOA6RC2H9MqR9jxA"target="_blank" class="ico ico-youtube"><i class="fab fa-youtube"></i></a>
                        {% include 'core/snippets/language_switcher.html' %}
                    </div>
                </div>
            </div>

            <div id="footer" class="text-muted">
                &copy; {{ year }} <a class="company-name" href="{{ service.url }}"><strong>{{ config.company_name }}</strong></a>.
                {% trans "All rights reserved." %}
                {% if config.legal_mentions_url %}
                - <a href="{{ config.legal_mentions_url }}" style="color: #666; text-decoration: none">{% trans "Legal mentions" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>